name: Check

on:
  pull_request

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v3.1.0
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Run detekt
        run: ./gradlew detekt :build-logic:detekt

  detekt_with_type_resolution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v3.1.0
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Run detekt with type resolution
        run: ./gradlew detektDevDebug

  validate_gradle_properties_match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1.0.4

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v3.1.0
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Validate that gradle property files are all equal
        run: ./gradlew validateGradleProperties
